// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4beta1/profile.proto

package com.google.cloud.talent.v4beta1;

public interface DegreeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4beta1.Degree)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ISCED degree type.
   * </pre>
   *
   * <code>.google.cloud.talent.v4beta1.DegreeType degree_type = 1;</code>
   * @return The enum numeric value on the wire for degreeType.
   */
  int getDegreeTypeValue();
  /**
   * <pre>
   * ISCED degree type.
   * </pre>
   *
   * <code>.google.cloud.talent.v4beta1.DegreeType degree_type = 1;</code>
   * @return The degreeType.
   */
  com.google.cloud.talent.v4beta1.DegreeType getDegreeType();

  /**
   * <pre>
   * Full Degree name.
   * For example, "B.S.", "Master of Arts", and so on.
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>string degree_name = 2;</code>
   * @return The degreeName.
   */
  java.lang.String getDegreeName();
  /**
   * <pre>
   * Full Degree name.
   * For example, "B.S.", "Master of Arts", and so on.
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>string degree_name = 2;</code>
   * @return The bytes for degreeName.
   */
  com.google.protobuf.ByteString
      getDegreeNameBytes();

  /**
   * <pre>
   * Fields of study for the degree.
   * For example, "Computer science", "engineering".
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>repeated string fields_of_study = 3;</code>
   * @return A list containing the fieldsOfStudy.
   */
  java.util.List<java.lang.String>
      getFieldsOfStudyList();
  /**
   * <pre>
   * Fields of study for the degree.
   * For example, "Computer science", "engineering".
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>repeated string fields_of_study = 3;</code>
   * @return The count of fieldsOfStudy.
   */
  int getFieldsOfStudyCount();
  /**
   * <pre>
   * Fields of study for the degree.
   * For example, "Computer science", "engineering".
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>repeated string fields_of_study = 3;</code>
   * @param index The index of the element to return.
   * @return The fieldsOfStudy at the given index.
   */
  java.lang.String getFieldsOfStudy(int index);
  /**
   * <pre>
   * Fields of study for the degree.
   * For example, "Computer science", "engineering".
   * Number of characters allowed is 100.
   * </pre>
   *
   * <code>repeated string fields_of_study = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldsOfStudy at the given index.
   */
  com.google.protobuf.ByteString
      getFieldsOfStudyBytes(int index);
}
