// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4beta1/profile.proto

package com.google.cloud.talent.v4beta1;

public interface PersonalUriOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4beta1.PersonalUri)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The personal URI.
   * Number of characters allowed is 4,000.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The uri.
   */
  java.lang.String getUri();
  /**
   * <pre>
   * The personal URI.
   * Number of characters allowed is 4,000.
   * </pre>
   *
   * <code>string uri = 1;</code>
   * @return The bytes for uri.
   */
  com.google.protobuf.ByteString
      getUriBytes();
}
