// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4beta1/filters.proto

package com.google.cloud.talent.v4beta1;

public interface SkillFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4beta1.SkillFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The skill name. For example, "java", "j2ee", and so on.
   * </pre>
   *
   * <code>string skill = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The skill.
   */
  java.lang.String getSkill();
  /**
   * <pre>
   * Required. The skill name. For example, "java", "j2ee", and so on.
   * </pre>
   *
   * <code>string skill = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for skill.
   */
  com.google.protobuf.ByteString
      getSkillBytes();

  /**
   * <pre>
   * Whether to apply negation to the filter so profiles matching the filter
   * are excluded.
   * </pre>
   *
   * <code>bool negated = 2;</code>
   * @return The negated.
   */
  boolean getNegated();
}
