// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4beta1/filters.proto

package com.google.cloud.talent.v4beta1;

public interface TimeFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4beta1.TimeFilter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Start timestamp, matching profiles with the start time. If this field
   * missing, The API matches profiles with create / update timestamp before the
   * end timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 1;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <pre>
   * Start timestamp, matching profiles with the start time. If this field
   * missing, The API matches profiles with create / update timestamp before the
   * end timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 1;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <pre>
   * Start timestamp, matching profiles with the start time. If this field
   * missing, The API matches profiles with create / update timestamp before the
   * end timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <pre>
   * End timestamp, matching profiles with the end time. If this field
   * missing, The API matches profiles with create / update timestamp after the
   * start timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <pre>
   * End timestamp, matching profiles with the end time. If this field
   * missing, The API matches profiles with create / update timestamp after the
   * start timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();
  /**
   * <pre>
   * End timestamp, matching profiles with the end time. If this field
   * missing, The API matches profiles with create / update timestamp after the
   * start timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();

  /**
   * <pre>
   * Specifies which time field to filter profiles.
   * Defaults to [TimeField.CREATE_TIME][google.cloud.talent.v4beta1.TimeFilter.TimeField.CREATE_TIME].
   * </pre>
   *
   * <code>.google.cloud.talent.v4beta1.TimeFilter.TimeField time_field = 3;</code>
   * @return The enum numeric value on the wire for timeField.
   */
  int getTimeFieldValue();
  /**
   * <pre>
   * Specifies which time field to filter profiles.
   * Defaults to [TimeField.CREATE_TIME][google.cloud.talent.v4beta1.TimeFilter.TimeField.CREATE_TIME].
   * </pre>
   *
   * <code>.google.cloud.talent.v4beta1.TimeFilter.TimeField time_field = 3;</code>
   * @return The timeField.
   */
  com.google.cloud.talent.v4beta1.TimeFilter.TimeField getTimeField();
}
