/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

/**
 *
 *
 * <pre>
 * Various debug options available for debugging mode. Internal only.
 * </pre>
 *
 * Protobuf type {@code google.cloud.talent.v4.DebugOptions}
 */
public final class DebugOptions extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.talent.v4.DebugOptions)
    DebugOptionsOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use DebugOptions.newBuilder() to construct.
  private DebugOptions(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private DebugOptions() {
    searcher_ = "";
    scoringParameterOverride_ = "";
    stExpressionOverride_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new DebugOptions();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private DebugOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8:
            {
              level_ = input.readInt32();
              break;
            }
          case 18:
            {
              java.lang.String s = input.readStringRequireUtf8();

              searcher_ = s;
              break;
            }
          case 26:
            {
              java.lang.String s = input.readStringRequireUtf8();

              scoringParameterOverride_ = s;
              break;
            }
          case 34:
            {
              java.lang.String s = input.readStringRequireUtf8();

              stExpressionOverride_ = s;
              break;
            }
          case 42:
            {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (searchAllTenant_ != null) {
                subBuilder = searchAllTenant_.toBuilder();
              }
              searchAllTenant_ =
                  input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(searchAllTenant_);
                searchAllTenant_ = subBuilder.buildPartial();
              }

              break;
            }
          case 50:
            {
              com.google.protobuf.BoolValue.Builder subBuilder = null;
              if (enableWildcardSearch_ != null) {
                subBuilder = enableWildcardSearch_.toBuilder();
              }
              enableWildcardSearch_ =
                  input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enableWildcardSearch_);
                enableWildcardSearch_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.talent.v4.CommonProto
        .internal_static_google_cloud_talent_v4_DebugOptions_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.talent.v4.CommonProto
        .internal_static_google_cloud_talent_v4_DebugOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.talent.v4.DebugOptions.class,
            com.google.cloud.talent.v4.DebugOptions.Builder.class);
  }

  public static final int LEVEL_FIELD_NUMBER = 1;
  private int level_;
  /**
   *
   *
   * <pre>
   * Specifies the level of debug output. The higher the number, the more
   * debug information is returned and printed in backend server logs.
   * Current levels are 1-4.
   * </pre>
   *
   * <code>int32 level = 1;</code>
   *
   * @return The level.
   */
  @java.lang.Override
  public int getLevel() {
    return level_;
  }

  public static final int SEARCHER_FIELD_NUMBER = 2;
  private volatile java.lang.Object searcher_;
  /**
   *
   *
   * <pre>
   * Specifies which search backend to use. Current available options are:
   * st-bti, model-t, and st-muppet.
   * </pre>
   *
   * <code>string searcher = 2;</code>
   *
   * @return The searcher.
   */
  @java.lang.Override
  public java.lang.String getSearcher() {
    java.lang.Object ref = searcher_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searcher_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Specifies which search backend to use. Current available options are:
   * st-bti, model-t, and st-muppet.
   * </pre>
   *
   * <code>string searcher = 2;</code>
   *
   * @return The bytes for searcher.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSearcherBytes() {
    java.lang.Object ref = searcher_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      searcher_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORING_PARAMETER_OVERRIDE_FIELD_NUMBER = 3;
  private volatile java.lang.Object scoringParameterOverride_;
  /**
   *
   *
   * <pre>
   * Specifies the scoring parameters to override during search. This is
   * equivalent to the 'dsp' url parameter in the legacy system. For details,
   * consult go/gjobs-scoring-params.
   * </pre>
   *
   * <code>string scoring_parameter_override = 3;</code>
   *
   * @return The scoringParameterOverride.
   */
  @java.lang.Override
  public java.lang.String getScoringParameterOverride() {
    java.lang.Object ref = scoringParameterOverride_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scoringParameterOverride_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Specifies the scoring parameters to override during search. This is
   * equivalent to the 'dsp' url parameter in the legacy system. For details,
   * consult go/gjobs-scoring-params.
   * </pre>
   *
   * <code>string scoring_parameter_override = 3;</code>
   *
   * @return The bytes for scoringParameterOverride.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getScoringParameterOverrideBytes() {
    java.lang.Object ref = scoringParameterOverride_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      scoringParameterOverride_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ST_EXPRESSION_OVERRIDE_FIELD_NUMBER = 4;
  private volatile java.lang.Object stExpressionOverride_;
  /**
   *
   *
   * <pre>
   * Overrides the ST sorting/scoring expression.
   * </pre>
   *
   * <code>string st_expression_override = 4;</code>
   *
   * @return The stExpressionOverride.
   */
  @java.lang.Override
  public java.lang.String getStExpressionOverride() {
    java.lang.Object ref = stExpressionOverride_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stExpressionOverride_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Overrides the ST sorting/scoring expression.
   * </pre>
   *
   * <code>string st_expression_override = 4;</code>
   *
   * @return The bytes for stExpressionOverride.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStExpressionOverrideBytes() {
    java.lang.Object ref = stExpressionOverride_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      stExpressionOverride_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEARCH_ALL_TENANT_FIELD_NUMBER = 5;
  private com.google.protobuf.BoolValue searchAllTenant_;
  /**
   *
   *
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   *
   * @return Whether the searchAllTenant field is set.
   */
  @java.lang.Override
  public boolean hasSearchAllTenant() {
    return searchAllTenant_ != null;
  }
  /**
   *
   *
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   *
   * @return The searchAllTenant.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getSearchAllTenant() {
    return searchAllTenant_ == null
        ? com.google.protobuf.BoolValue.getDefaultInstance()
        : searchAllTenant_;
  }
  /**
   *
   *
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getSearchAllTenantOrBuilder() {
    return getSearchAllTenant();
  }

  public static final int ENABLE_WILDCARD_SEARCH_FIELD_NUMBER = 6;
  private com.google.protobuf.BoolValue enableWildcardSearch_;
  /**
   *
   *
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   *
   * @return Whether the enableWildcardSearch field is set.
   */
  @java.lang.Override
  public boolean hasEnableWildcardSearch() {
    return enableWildcardSearch_ != null;
  }
  /**
   *
   *
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   *
   * @return The enableWildcardSearch.
   */
  @java.lang.Override
  public com.google.protobuf.BoolValue getEnableWildcardSearch() {
    return enableWildcardSearch_ == null
        ? com.google.protobuf.BoolValue.getDefaultInstance()
        : enableWildcardSearch_;
  }
  /**
   *
   *
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.BoolValueOrBuilder getEnableWildcardSearchOrBuilder() {
    return getEnableWildcardSearch();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (level_ != 0) {
      output.writeInt32(1, level_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searcher_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, searcher_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoringParameterOverride_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, scoringParameterOverride_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stExpressionOverride_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, stExpressionOverride_);
    }
    if (searchAllTenant_ != null) {
      output.writeMessage(5, getSearchAllTenant());
    }
    if (enableWildcardSearch_ != null) {
      output.writeMessage(6, getEnableWildcardSearch());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (level_ != 0) {
      size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, level_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(searcher_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, searcher_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(scoringParameterOverride_)) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(3, scoringParameterOverride_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stExpressionOverride_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, stExpressionOverride_);
    }
    if (searchAllTenant_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, getSearchAllTenant());
    }
    if (enableWildcardSearch_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(6, getEnableWildcardSearch());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.talent.v4.DebugOptions)) {
      return super.equals(obj);
    }
    com.google.cloud.talent.v4.DebugOptions other = (com.google.cloud.talent.v4.DebugOptions) obj;

    if (getLevel() != other.getLevel()) return false;
    if (!getSearcher().equals(other.getSearcher())) return false;
    if (!getScoringParameterOverride().equals(other.getScoringParameterOverride())) return false;
    if (!getStExpressionOverride().equals(other.getStExpressionOverride())) return false;
    if (hasSearchAllTenant() != other.hasSearchAllTenant()) return false;
    if (hasSearchAllTenant()) {
      if (!getSearchAllTenant().equals(other.getSearchAllTenant())) return false;
    }
    if (hasEnableWildcardSearch() != other.hasEnableWildcardSearch()) return false;
    if (hasEnableWildcardSearch()) {
      if (!getEnableWildcardSearch().equals(other.getEnableWildcardSearch())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel();
    hash = (37 * hash) + SEARCHER_FIELD_NUMBER;
    hash = (53 * hash) + getSearcher().hashCode();
    hash = (37 * hash) + SCORING_PARAMETER_OVERRIDE_FIELD_NUMBER;
    hash = (53 * hash) + getScoringParameterOverride().hashCode();
    hash = (37 * hash) + ST_EXPRESSION_OVERRIDE_FIELD_NUMBER;
    hash = (53 * hash) + getStExpressionOverride().hashCode();
    if (hasSearchAllTenant()) {
      hash = (37 * hash) + SEARCH_ALL_TENANT_FIELD_NUMBER;
      hash = (53 * hash) + getSearchAllTenant().hashCode();
    }
    if (hasEnableWildcardSearch()) {
      hash = (37 * hash) + ENABLE_WILDCARD_SEARCH_FIELD_NUMBER;
      hash = (53 * hash) + getEnableWildcardSearch().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.talent.v4.DebugOptions prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Various debug options available for debugging mode. Internal only.
   * </pre>
   *
   * Protobuf type {@code google.cloud.talent.v4.DebugOptions}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.talent.v4.DebugOptions)
      com.google.cloud.talent.v4.DebugOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugOptions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.talent.v4.DebugOptions.class,
              com.google.cloud.talent.v4.DebugOptions.Builder.class);
    }

    // Construct using com.google.cloud.talent.v4.DebugOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      level_ = 0;

      searcher_ = "";

      scoringParameterOverride_ = "";

      stExpressionOverride_ = "";

      if (searchAllTenantBuilder_ == null) {
        searchAllTenant_ = null;
      } else {
        searchAllTenant_ = null;
        searchAllTenantBuilder_ = null;
      }
      if (enableWildcardSearchBuilder_ == null) {
        enableWildcardSearch_ = null;
      } else {
        enableWildcardSearch_ = null;
        enableWildcardSearchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugOptions_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugOptions getDefaultInstanceForType() {
      return com.google.cloud.talent.v4.DebugOptions.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugOptions build() {
      com.google.cloud.talent.v4.DebugOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugOptions buildPartial() {
      com.google.cloud.talent.v4.DebugOptions result =
          new com.google.cloud.talent.v4.DebugOptions(this);
      result.level_ = level_;
      result.searcher_ = searcher_;
      result.scoringParameterOverride_ = scoringParameterOverride_;
      result.stExpressionOverride_ = stExpressionOverride_;
      if (searchAllTenantBuilder_ == null) {
        result.searchAllTenant_ = searchAllTenant_;
      } else {
        result.searchAllTenant_ = searchAllTenantBuilder_.build();
      }
      if (enableWildcardSearchBuilder_ == null) {
        result.enableWildcardSearch_ = enableWildcardSearch_;
      } else {
        result.enableWildcardSearch_ = enableWildcardSearchBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.talent.v4.DebugOptions) {
        return mergeFrom((com.google.cloud.talent.v4.DebugOptions) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.talent.v4.DebugOptions other) {
      if (other == com.google.cloud.talent.v4.DebugOptions.getDefaultInstance()) return this;
      if (other.getLevel() != 0) {
        setLevel(other.getLevel());
      }
      if (!other.getSearcher().isEmpty()) {
        searcher_ = other.searcher_;
        onChanged();
      }
      if (!other.getScoringParameterOverride().isEmpty()) {
        scoringParameterOverride_ = other.scoringParameterOverride_;
        onChanged();
      }
      if (!other.getStExpressionOverride().isEmpty()) {
        stExpressionOverride_ = other.stExpressionOverride_;
        onChanged();
      }
      if (other.hasSearchAllTenant()) {
        mergeSearchAllTenant(other.getSearchAllTenant());
      }
      if (other.hasEnableWildcardSearch()) {
        mergeEnableWildcardSearch(other.getEnableWildcardSearch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.talent.v4.DebugOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.talent.v4.DebugOptions) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int level_;
    /**
     *
     *
     * <pre>
     * Specifies the level of debug output. The higher the number, the more
     * debug information is returned and printed in backend server logs.
     * Current levels are 1-4.
     * </pre>
     *
     * <code>int32 level = 1;</code>
     *
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }
    /**
     *
     *
     * <pre>
     * Specifies the level of debug output. The higher the number, the more
     * debug information is returned and printed in backend server logs.
     * Current levels are 1-4.
     * </pre>
     *
     * <code>int32 level = 1;</code>
     *
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(int value) {

      level_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Specifies the level of debug output. The higher the number, the more
     * debug information is returned and printed in backend server logs.
     * Current levels are 1-4.
     * </pre>
     *
     * <code>int32 level = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearLevel() {

      level_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object searcher_ = "";
    /**
     *
     *
     * <pre>
     * Specifies which search backend to use. Current available options are:
     * st-bti, model-t, and st-muppet.
     * </pre>
     *
     * <code>string searcher = 2;</code>
     *
     * @return The searcher.
     */
    public java.lang.String getSearcher() {
      java.lang.Object ref = searcher_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searcher_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Specifies which search backend to use. Current available options are:
     * st-bti, model-t, and st-muppet.
     * </pre>
     *
     * <code>string searcher = 2;</code>
     *
     * @return The bytes for searcher.
     */
    public com.google.protobuf.ByteString getSearcherBytes() {
      java.lang.Object ref = searcher_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        searcher_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Specifies which search backend to use. Current available options are:
     * st-bti, model-t, and st-muppet.
     * </pre>
     *
     * <code>string searcher = 2;</code>
     *
     * @param value The searcher to set.
     * @return This builder for chaining.
     */
    public Builder setSearcher(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      searcher_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Specifies which search backend to use. Current available options are:
     * st-bti, model-t, and st-muppet.
     * </pre>
     *
     * <code>string searcher = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSearcher() {

      searcher_ = getDefaultInstance().getSearcher();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Specifies which search backend to use. Current available options are:
     * st-bti, model-t, and st-muppet.
     * </pre>
     *
     * <code>string searcher = 2;</code>
     *
     * @param value The bytes for searcher to set.
     * @return This builder for chaining.
     */
    public Builder setSearcherBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      searcher_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scoringParameterOverride_ = "";
    /**
     *
     *
     * <pre>
     * Specifies the scoring parameters to override during search. This is
     * equivalent to the 'dsp' url parameter in the legacy system. For details,
     * consult go/gjobs-scoring-params.
     * </pre>
     *
     * <code>string scoring_parameter_override = 3;</code>
     *
     * @return The scoringParameterOverride.
     */
    public java.lang.String getScoringParameterOverride() {
      java.lang.Object ref = scoringParameterOverride_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scoringParameterOverride_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Specifies the scoring parameters to override during search. This is
     * equivalent to the 'dsp' url parameter in the legacy system. For details,
     * consult go/gjobs-scoring-params.
     * </pre>
     *
     * <code>string scoring_parameter_override = 3;</code>
     *
     * @return The bytes for scoringParameterOverride.
     */
    public com.google.protobuf.ByteString getScoringParameterOverrideBytes() {
      java.lang.Object ref = scoringParameterOverride_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        scoringParameterOverride_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Specifies the scoring parameters to override during search. This is
     * equivalent to the 'dsp' url parameter in the legacy system. For details,
     * consult go/gjobs-scoring-params.
     * </pre>
     *
     * <code>string scoring_parameter_override = 3;</code>
     *
     * @param value The scoringParameterOverride to set.
     * @return This builder for chaining.
     */
    public Builder setScoringParameterOverride(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      scoringParameterOverride_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Specifies the scoring parameters to override during search. This is
     * equivalent to the 'dsp' url parameter in the legacy system. For details,
     * consult go/gjobs-scoring-params.
     * </pre>
     *
     * <code>string scoring_parameter_override = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearScoringParameterOverride() {

      scoringParameterOverride_ = getDefaultInstance().getScoringParameterOverride();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Specifies the scoring parameters to override during search. This is
     * equivalent to the 'dsp' url parameter in the legacy system. For details,
     * consult go/gjobs-scoring-params.
     * </pre>
     *
     * <code>string scoring_parameter_override = 3;</code>
     *
     * @param value The bytes for scoringParameterOverride to set.
     * @return This builder for chaining.
     */
    public Builder setScoringParameterOverrideBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      scoringParameterOverride_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object stExpressionOverride_ = "";
    /**
     *
     *
     * <pre>
     * Overrides the ST sorting/scoring expression.
     * </pre>
     *
     * <code>string st_expression_override = 4;</code>
     *
     * @return The stExpressionOverride.
     */
    public java.lang.String getStExpressionOverride() {
      java.lang.Object ref = stExpressionOverride_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stExpressionOverride_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Overrides the ST sorting/scoring expression.
     * </pre>
     *
     * <code>string st_expression_override = 4;</code>
     *
     * @return The bytes for stExpressionOverride.
     */
    public com.google.protobuf.ByteString getStExpressionOverrideBytes() {
      java.lang.Object ref = stExpressionOverride_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        stExpressionOverride_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Overrides the ST sorting/scoring expression.
     * </pre>
     *
     * <code>string st_expression_override = 4;</code>
     *
     * @param value The stExpressionOverride to set.
     * @return This builder for chaining.
     */
    public Builder setStExpressionOverride(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      stExpressionOverride_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Overrides the ST sorting/scoring expression.
     * </pre>
     *
     * <code>string st_expression_override = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearStExpressionOverride() {

      stExpressionOverride_ = getDefaultInstance().getStExpressionOverride();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Overrides the ST sorting/scoring expression.
     * </pre>
     *
     * <code>string st_expression_override = 4;</code>
     *
     * @param value The bytes for stExpressionOverride to set.
     * @return This builder for chaining.
     */
    public Builder setStExpressionOverrideBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      stExpressionOverride_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.BoolValue searchAllTenant_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue,
            com.google.protobuf.BoolValue.Builder,
            com.google.protobuf.BoolValueOrBuilder>
        searchAllTenantBuilder_;
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     *
     * @return Whether the searchAllTenant field is set.
     */
    public boolean hasSearchAllTenant() {
      return searchAllTenantBuilder_ != null || searchAllTenant_ != null;
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     *
     * @return The searchAllTenant.
     */
    public com.google.protobuf.BoolValue getSearchAllTenant() {
      if (searchAllTenantBuilder_ == null) {
        return searchAllTenant_ == null
            ? com.google.protobuf.BoolValue.getDefaultInstance()
            : searchAllTenant_;
      } else {
        return searchAllTenantBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public Builder setSearchAllTenant(com.google.protobuf.BoolValue value) {
      if (searchAllTenantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        searchAllTenant_ = value;
        onChanged();
      } else {
        searchAllTenantBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public Builder setSearchAllTenant(com.google.protobuf.BoolValue.Builder builderForValue) {
      if (searchAllTenantBuilder_ == null) {
        searchAllTenant_ = builderForValue.build();
        onChanged();
      } else {
        searchAllTenantBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public Builder mergeSearchAllTenant(com.google.protobuf.BoolValue value) {
      if (searchAllTenantBuilder_ == null) {
        if (searchAllTenant_ != null) {
          searchAllTenant_ =
              com.google.protobuf.BoolValue.newBuilder(searchAllTenant_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          searchAllTenant_ = value;
        }
        onChanged();
      } else {
        searchAllTenantBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public Builder clearSearchAllTenant() {
      if (searchAllTenantBuilder_ == null) {
        searchAllTenant_ = null;
        onChanged();
      } else {
        searchAllTenant_ = null;
        searchAllTenantBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public com.google.protobuf.BoolValue.Builder getSearchAllTenantBuilder() {

      onChanged();
      return getSearchAllTenantFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getSearchAllTenantOrBuilder() {
      if (searchAllTenantBuilder_ != null) {
        return searchAllTenantBuilder_.getMessageOrBuilder();
      } else {
        return searchAllTenant_ == null
            ? com.google.protobuf.BoolValue.getDefaultInstance()
            : searchAllTenant_;
      }
    }
    /**
     *
     *
     * <pre>
     * Search documents of all tenants (only implemented for job search as of
     * 6/14/2019).
     * </pre>
     *
     * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue,
            com.google.protobuf.BoolValue.Builder,
            com.google.protobuf.BoolValueOrBuilder>
        getSearchAllTenantFieldBuilder() {
      if (searchAllTenantBuilder_ == null) {
        searchAllTenantBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.BoolValue,
                com.google.protobuf.BoolValue.Builder,
                com.google.protobuf.BoolValueOrBuilder>(
                getSearchAllTenant(), getParentForChildren(), isClean());
        searchAllTenant_ = null;
      }
      return searchAllTenantBuilder_;
    }

    private com.google.protobuf.BoolValue enableWildcardSearch_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue,
            com.google.protobuf.BoolValue.Builder,
            com.google.protobuf.BoolValueOrBuilder>
        enableWildcardSearchBuilder_;
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     *
     * @return Whether the enableWildcardSearch field is set.
     */
    public boolean hasEnableWildcardSearch() {
      return enableWildcardSearchBuilder_ != null || enableWildcardSearch_ != null;
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     *
     * @return The enableWildcardSearch.
     */
    public com.google.protobuf.BoolValue getEnableWildcardSearch() {
      if (enableWildcardSearchBuilder_ == null) {
        return enableWildcardSearch_ == null
            ? com.google.protobuf.BoolValue.getDefaultInstance()
            : enableWildcardSearch_;
      } else {
        return enableWildcardSearchBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public Builder setEnableWildcardSearch(com.google.protobuf.BoolValue value) {
      if (enableWildcardSearchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        enableWildcardSearch_ = value;
        onChanged();
      } else {
        enableWildcardSearchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public Builder setEnableWildcardSearch(com.google.protobuf.BoolValue.Builder builderForValue) {
      if (enableWildcardSearchBuilder_ == null) {
        enableWildcardSearch_ = builderForValue.build();
        onChanged();
      } else {
        enableWildcardSearchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public Builder mergeEnableWildcardSearch(com.google.protobuf.BoolValue value) {
      if (enableWildcardSearchBuilder_ == null) {
        if (enableWildcardSearch_ != null) {
          enableWildcardSearch_ =
              com.google.protobuf.BoolValue.newBuilder(enableWildcardSearch_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          enableWildcardSearch_ = value;
        }
        onChanged();
      } else {
        enableWildcardSearchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public Builder clearEnableWildcardSearch() {
      if (enableWildcardSearchBuilder_ == null) {
        enableWildcardSearch_ = null;
        onChanged();
      } else {
        enableWildcardSearch_ = null;
        enableWildcardSearchBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public com.google.protobuf.BoolValue.Builder getEnableWildcardSearchBuilder() {

      onChanged();
      return getEnableWildcardSearchFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getEnableWildcardSearchOrBuilder() {
      if (enableWildcardSearchBuilder_ != null) {
        return enableWildcardSearchBuilder_.getMessageOrBuilder();
      } else {
        return enableWildcardSearch_ == null
            ? com.google.protobuf.BoolValue.getDefaultInstance()
            : enableWildcardSearch_;
      }
    }
    /**
     *
     *
     * <pre>
     * Temporarily added this flag for profile wildcard search
     * Flag to indicate whether wildcard search is enabled
     * </pre>
     *
     * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue,
            com.google.protobuf.BoolValue.Builder,
            com.google.protobuf.BoolValueOrBuilder>
        getEnableWildcardSearchFieldBuilder() {
      if (enableWildcardSearchBuilder_ == null) {
        enableWildcardSearchBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.BoolValue,
                com.google.protobuf.BoolValue.Builder,
                com.google.protobuf.BoolValueOrBuilder>(
                getEnableWildcardSearch(), getParentForChildren(), isClean());
        enableWildcardSearch_ = null;
      }
      return enableWildcardSearchBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.talent.v4.DebugOptions)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.talent.v4.DebugOptions)
  private static final com.google.cloud.talent.v4.DebugOptions DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.talent.v4.DebugOptions();
  }

  public static com.google.cloud.talent.v4.DebugOptions getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DebugOptions> PARSER =
      new com.google.protobuf.AbstractParser<DebugOptions>() {
        @java.lang.Override
        public DebugOptions parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DebugOptions(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<DebugOptions> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DebugOptions> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.talent.v4.DebugOptions getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
