/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

public interface DebugInfoOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.DebugInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query_debug_info = 1;</code>
   *
   * @return The queryDebugInfo.
   */
  java.lang.String getQueryDebugInfo();
  /**
   * <code>string query_debug_info = 1;</code>
   *
   * @return The bytes for queryDebugInfo.
   */
  com.google.protobuf.ByteString getQueryDebugInfoBytes();

  /**
   * <code>string moonshine_debug_info = 2;</code>
   *
   * @return The moonshineDebugInfo.
   */
  java.lang.String getMoonshineDebugInfo();
  /**
   * <code>string moonshine_debug_info = 2;</code>
   *
   * @return The bytes for moonshineDebugInfo.
   */
  com.google.protobuf.ByteString getMoonshineDebugInfoBytes();

  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @return A list containing the experimentIds.
   */
  java.util.List<java.lang.Integer> getExperimentIdsList();
  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @return The count of experimentIds.
   */
  int getExperimentIdsCount();
  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @param index The index of the element to return.
   * @return The experimentIds at the given index.
   */
  int getExperimentIds(int index);

  /**
   *
   *
   * <pre>
   * The model id for profiles recommendation.
   * </pre>
   *
   * <code>string recommend_model_id = 4;</code>
   *
   * @return The recommendModelId.
   */
  java.lang.String getRecommendModelId();
  /**
   *
   *
   * <pre>
   * The model id for profiles recommendation.
   * </pre>
   *
   * <code>string recommend_model_id = 4;</code>
   *
   * @return The bytes for recommendModelId.
   */
  com.google.protobuf.ByteString getRecommendModelIdBytes();
}
