/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

/**
 *
 *
 * <pre>
 * Debug information.
 * </pre>
 *
 * Protobuf type {@code google.cloud.talent.v4.DebugInfo}
 */
public final class DebugInfo extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.talent.v4.DebugInfo)
    DebugInfoOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use DebugInfo.newBuilder() to construct.
  private DebugInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private DebugInfo() {
    queryDebugInfo_ = "";
    moonshineDebugInfo_ = "";
    experimentIds_ = emptyIntList();
    recommendModelId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new DebugInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private DebugInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              queryDebugInfo_ = s;
              break;
            }
          case 18:
            {
              java.lang.String s = input.readStringRequireUtf8();

              moonshineDebugInfo_ = s;
              break;
            }
          case 24:
            {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                experimentIds_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              experimentIds_.addInt(input.readInt32());
              break;
            }
          case 26:
            {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                experimentIds_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                experimentIds_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          case 34:
            {
              java.lang.String s = input.readStringRequireUtf8();

              recommendModelId_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        experimentIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.cloud.talent.v4.CommonProto
        .internal_static_google_cloud_talent_v4_DebugInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.talent.v4.CommonProto
        .internal_static_google_cloud_talent_v4_DebugInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.talent.v4.DebugInfo.class,
            com.google.cloud.talent.v4.DebugInfo.Builder.class);
  }

  public static final int QUERY_DEBUG_INFO_FIELD_NUMBER = 1;
  private volatile java.lang.Object queryDebugInfo_;
  /**
   * <code>string query_debug_info = 1;</code>
   *
   * @return The queryDebugInfo.
   */
  @java.lang.Override
  public java.lang.String getQueryDebugInfo() {
    java.lang.Object ref = queryDebugInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queryDebugInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string query_debug_info = 1;</code>
   *
   * @return The bytes for queryDebugInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getQueryDebugInfoBytes() {
    java.lang.Object ref = queryDebugInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      queryDebugInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOONSHINE_DEBUG_INFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object moonshineDebugInfo_;
  /**
   * <code>string moonshine_debug_info = 2;</code>
   *
   * @return The moonshineDebugInfo.
   */
  @java.lang.Override
  public java.lang.String getMoonshineDebugInfo() {
    java.lang.Object ref = moonshineDebugInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      moonshineDebugInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string moonshine_debug_info = 2;</code>
   *
   * @return The bytes for moonshineDebugInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMoonshineDebugInfoBytes() {
    java.lang.Object ref = moonshineDebugInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      moonshineDebugInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPERIMENT_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList experimentIds_;
  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @return A list containing the experimentIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer> getExperimentIdsList() {
    return experimentIds_;
  }
  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @return The count of experimentIds.
   */
  public int getExperimentIdsCount() {
    return experimentIds_.size();
  }
  /**
   *
   *
   * <pre>
   * Identifiers for the versions of the search algorithm used during
   * this API invocation if multiple algorithms are used.
   * The default value is empty.
   * </pre>
   *
   * <code>repeated int32 experiment_ids = 3;</code>
   *
   * @param index The index of the element to return.
   * @return The experimentIds at the given index.
   */
  public int getExperimentIds(int index) {
    return experimentIds_.getInt(index);
  }

  private int experimentIdsMemoizedSerializedSize = -1;

  public static final int RECOMMEND_MODEL_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object recommendModelId_;
  /**
   *
   *
   * <pre>
   * The model id for profiles recommendation.
   * </pre>
   *
   * <code>string recommend_model_id = 4;</code>
   *
   * @return The recommendModelId.
   */
  @java.lang.Override
  public java.lang.String getRecommendModelId() {
    java.lang.Object ref = recommendModelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recommendModelId_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The model id for profiles recommendation.
   * </pre>
   *
   * <code>string recommend_model_id = 4;</code>
   *
   * @return The bytes for recommendModelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRecommendModelIdBytes() {
    java.lang.Object ref = recommendModelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      recommendModelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queryDebugInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queryDebugInfo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moonshineDebugInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, moonshineDebugInfo_);
    }
    if (getExperimentIdsList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(experimentIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < experimentIds_.size(); i++) {
      output.writeInt32NoTag(experimentIds_.getInt(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recommendModelId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, recommendModelId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(queryDebugInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, queryDebugInfo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moonshineDebugInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, moonshineDebugInfo_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < experimentIds_.size(); i++) {
        dataSize +=
            com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(experimentIds_.getInt(i));
      }
      size += dataSize;
      if (!getExperimentIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(dataSize);
      }
      experimentIdsMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recommendModelId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, recommendModelId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.cloud.talent.v4.DebugInfo)) {
      return super.equals(obj);
    }
    com.google.cloud.talent.v4.DebugInfo other = (com.google.cloud.talent.v4.DebugInfo) obj;

    if (!getQueryDebugInfo().equals(other.getQueryDebugInfo())) return false;
    if (!getMoonshineDebugInfo().equals(other.getMoonshineDebugInfo())) return false;
    if (!getExperimentIdsList().equals(other.getExperimentIdsList())) return false;
    if (!getRecommendModelId().equals(other.getRecommendModelId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUERY_DEBUG_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getQueryDebugInfo().hashCode();
    hash = (37 * hash) + MOONSHINE_DEBUG_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getMoonshineDebugInfo().hashCode();
    if (getExperimentIdsCount() > 0) {
      hash = (37 * hash) + EXPERIMENT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getExperimentIdsList().hashCode();
    }
    hash = (37 * hash) + RECOMMEND_MODEL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRecommendModelId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.cloud.talent.v4.DebugInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.cloud.talent.v4.DebugInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Debug information.
   * </pre>
   *
   * Protobuf type {@code google.cloud.talent.v4.DebugInfo}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.talent.v4.DebugInfo)
      com.google.cloud.talent.v4.DebugInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.talent.v4.DebugInfo.class,
              com.google.cloud.talent.v4.DebugInfo.Builder.class);
    }

    // Construct using com.google.cloud.talent.v4.DebugInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      queryDebugInfo_ = "";

      moonshineDebugInfo_ = "";

      experimentIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      recommendModelId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.cloud.talent.v4.CommonProto
          .internal_static_google_cloud_talent_v4_DebugInfo_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugInfo getDefaultInstanceForType() {
      return com.google.cloud.talent.v4.DebugInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugInfo build() {
      com.google.cloud.talent.v4.DebugInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DebugInfo buildPartial() {
      com.google.cloud.talent.v4.DebugInfo result = new com.google.cloud.talent.v4.DebugInfo(this);
      int from_bitField0_ = bitField0_;
      result.queryDebugInfo_ = queryDebugInfo_;
      result.moonshineDebugInfo_ = moonshineDebugInfo_;
      if (((bitField0_ & 0x00000001) != 0)) {
        experimentIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.experimentIds_ = experimentIds_;
      result.recommendModelId_ = recommendModelId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.talent.v4.DebugInfo) {
        return mergeFrom((com.google.cloud.talent.v4.DebugInfo) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.talent.v4.DebugInfo other) {
      if (other == com.google.cloud.talent.v4.DebugInfo.getDefaultInstance()) return this;
      if (!other.getQueryDebugInfo().isEmpty()) {
        queryDebugInfo_ = other.queryDebugInfo_;
        onChanged();
      }
      if (!other.getMoonshineDebugInfo().isEmpty()) {
        moonshineDebugInfo_ = other.moonshineDebugInfo_;
        onChanged();
      }
      if (!other.experimentIds_.isEmpty()) {
        if (experimentIds_.isEmpty()) {
          experimentIds_ = other.experimentIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureExperimentIdsIsMutable();
          experimentIds_.addAll(other.experimentIds_);
        }
        onChanged();
      }
      if (!other.getRecommendModelId().isEmpty()) {
        recommendModelId_ = other.recommendModelId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.talent.v4.DebugInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.talent.v4.DebugInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object queryDebugInfo_ = "";
    /**
     * <code>string query_debug_info = 1;</code>
     *
     * @return The queryDebugInfo.
     */
    public java.lang.String getQueryDebugInfo() {
      java.lang.Object ref = queryDebugInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queryDebugInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string query_debug_info = 1;</code>
     *
     * @return The bytes for queryDebugInfo.
     */
    public com.google.protobuf.ByteString getQueryDebugInfoBytes() {
      java.lang.Object ref = queryDebugInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        queryDebugInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string query_debug_info = 1;</code>
     *
     * @param value The queryDebugInfo to set.
     * @return This builder for chaining.
     */
    public Builder setQueryDebugInfo(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      queryDebugInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string query_debug_info = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearQueryDebugInfo() {

      queryDebugInfo_ = getDefaultInstance().getQueryDebugInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string query_debug_info = 1;</code>
     *
     * @param value The bytes for queryDebugInfo to set.
     * @return This builder for chaining.
     */
    public Builder setQueryDebugInfoBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      queryDebugInfo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object moonshineDebugInfo_ = "";
    /**
     * <code>string moonshine_debug_info = 2;</code>
     *
     * @return The moonshineDebugInfo.
     */
    public java.lang.String getMoonshineDebugInfo() {
      java.lang.Object ref = moonshineDebugInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        moonshineDebugInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string moonshine_debug_info = 2;</code>
     *
     * @return The bytes for moonshineDebugInfo.
     */
    public com.google.protobuf.ByteString getMoonshineDebugInfoBytes() {
      java.lang.Object ref = moonshineDebugInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        moonshineDebugInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string moonshine_debug_info = 2;</code>
     *
     * @param value The moonshineDebugInfo to set.
     * @return This builder for chaining.
     */
    public Builder setMoonshineDebugInfo(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      moonshineDebugInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string moonshine_debug_info = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMoonshineDebugInfo() {

      moonshineDebugInfo_ = getDefaultInstance().getMoonshineDebugInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string moonshine_debug_info = 2;</code>
     *
     * @param value The bytes for moonshineDebugInfo to set.
     * @return This builder for chaining.
     */
    public Builder setMoonshineDebugInfoBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      moonshineDebugInfo_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList experimentIds_ = emptyIntList();

    private void ensureExperimentIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        experimentIds_ = mutableCopy(experimentIds_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @return A list containing the experimentIds.
     */
    public java.util.List<java.lang.Integer> getExperimentIdsList() {
      return ((bitField0_ & 0x00000001) != 0)
          ? java.util.Collections.unmodifiableList(experimentIds_)
          : experimentIds_;
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @return The count of experimentIds.
     */
    public int getExperimentIdsCount() {
      return experimentIds_.size();
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The experimentIds at the given index.
     */
    public int getExperimentIds(int index) {
      return experimentIds_.getInt(index);
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @param index The index to set the value at.
     * @param value The experimentIds to set.
     * @return This builder for chaining.
     */
    public Builder setExperimentIds(int index, int value) {
      ensureExperimentIdsIsMutable();
      experimentIds_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @param value The experimentIds to add.
     * @return This builder for chaining.
     */
    public Builder addExperimentIds(int value) {
      ensureExperimentIdsIsMutable();
      experimentIds_.addInt(value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @param values The experimentIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllExperimentIds(java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureExperimentIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, experimentIds_);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Identifiers for the versions of the search algorithm used during
     * this API invocation if multiple algorithms are used.
     * The default value is empty.
     * </pre>
     *
     * <code>repeated int32 experiment_ids = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearExperimentIds() {
      experimentIds_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.lang.Object recommendModelId_ = "";
    /**
     *
     *
     * <pre>
     * The model id for profiles recommendation.
     * </pre>
     *
     * <code>string recommend_model_id = 4;</code>
     *
     * @return The recommendModelId.
     */
    public java.lang.String getRecommendModelId() {
      java.lang.Object ref = recommendModelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recommendModelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The model id for profiles recommendation.
     * </pre>
     *
     * <code>string recommend_model_id = 4;</code>
     *
     * @return The bytes for recommendModelId.
     */
    public com.google.protobuf.ByteString getRecommendModelIdBytes() {
      java.lang.Object ref = recommendModelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        recommendModelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The model id for profiles recommendation.
     * </pre>
     *
     * <code>string recommend_model_id = 4;</code>
     *
     * @param value The recommendModelId to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendModelId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      recommendModelId_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The model id for profiles recommendation.
     * </pre>
     *
     * <code>string recommend_model_id = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRecommendModelId() {

      recommendModelId_ = getDefaultInstance().getRecommendModelId();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The model id for profiles recommendation.
     * </pre>
     *
     * <code>string recommend_model_id = 4;</code>
     *
     * @param value The bytes for recommendModelId to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendModelIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      recommendModelId_ = value;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.talent.v4.DebugInfo)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.talent.v4.DebugInfo)
  private static final com.google.cloud.talent.v4.DebugInfo DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.cloud.talent.v4.DebugInfo();
  }

  public static com.google.cloud.talent.v4.DebugInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DebugInfo> PARSER =
      new com.google.protobuf.AbstractParser<DebugInfo>() {
        @java.lang.Override
        public DebugInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DebugInfo(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<DebugInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DebugInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.talent.v4.DebugInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
