/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/job_service.proto

package com.google.cloud.talent.v4;

public interface PurgeJobsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.PurgeJobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The number of jobs that this request deleted (or, if `force` is false,
   * the number of jobs that will be deleted).
   * Note: This number isn't guaranteed to be accurate.
   * Note: This number might change until operation status is FINISHED, FAILED
   * or CANCELLED.
   * </pre>
   *
   * <code>int32 purge_count = 1;</code>
   *
   * @return The purgeCount.
   */
  int getPurgeCount();

  /**
   *
   *
   * <pre>
   * A sample of the resource names of jobs that will be deleted.
   * Only populated if `force` is set to false.
   * At most 100 job names are returned as a sample.
   * </pre>
   *
   * <code>repeated string purge_sample = 2;</code>
   *
   * @return A list containing the purgeSample.
   */
  java.util.List<java.lang.String> getPurgeSampleList();
  /**
   *
   *
   * <pre>
   * A sample of the resource names of jobs that will be deleted.
   * Only populated if `force` is set to false.
   * At most 100 job names are returned as a sample.
   * </pre>
   *
   * <code>repeated string purge_sample = 2;</code>
   *
   * @return The count of purgeSample.
   */
  int getPurgeSampleCount();
  /**
   *
   *
   * <pre>
   * A sample of the resource names of jobs that will be deleted.
   * Only populated if `force` is set to false.
   * At most 100 job names are returned as a sample.
   * </pre>
   *
   * <code>repeated string purge_sample = 2;</code>
   *
   * @param index The index of the element to return.
   * @return The purgeSample at the given index.
   */
  java.lang.String getPurgeSample(int index);
  /**
   *
   *
   * <pre>
   * A sample of the resource names of jobs that will be deleted.
   * Only populated if `force` is set to false.
   * At most 100 job names are returned as a sample.
   * </pre>
   *
   * <code>repeated string purge_sample = 2;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the purgeSample at the given index.
   */
  com.google.protobuf.ByteString getPurgeSampleBytes(int index);

  /**
   *
   *
   * <pre>
   * List of job purge results from a purge jobs operation.
   * Only populated if `force` is set to true.
   * Note: This may change until operation status is FINISHED, FAILED or
   * CANCELLED.
   * </pre>
   *
   * <code>repeated .google.cloud.talent.v4.JobResult job_results = 3;</code>
   */
  java.util.List<com.google.cloud.talent.v4.JobResult> getJobResultsList();
  /**
   *
   *
   * <pre>
   * List of job purge results from a purge jobs operation.
   * Only populated if `force` is set to true.
   * Note: This may change until operation status is FINISHED, FAILED or
   * CANCELLED.
   * </pre>
   *
   * <code>repeated .google.cloud.talent.v4.JobResult job_results = 3;</code>
   */
  com.google.cloud.talent.v4.JobResult getJobResults(int index);
  /**
   *
   *
   * <pre>
   * List of job purge results from a purge jobs operation.
   * Only populated if `force` is set to true.
   * Note: This may change until operation status is FINISHED, FAILED or
   * CANCELLED.
   * </pre>
   *
   * <code>repeated .google.cloud.talent.v4.JobResult job_results = 3;</code>
   */
  int getJobResultsCount();
  /**
   *
   *
   * <pre>
   * List of job purge results from a purge jobs operation.
   * Only populated if `force` is set to true.
   * Note: This may change until operation status is FINISHED, FAILED or
   * CANCELLED.
   * </pre>
   *
   * <code>repeated .google.cloud.talent.v4.JobResult job_results = 3;</code>
   */
  java.util.List<? extends com.google.cloud.talent.v4.JobResultOrBuilder>
      getJobResultsOrBuilderList();
  /**
   *
   *
   * <pre>
   * List of job purge results from a purge jobs operation.
   * Only populated if `force` is set to true.
   * Note: This may change until operation status is FINISHED, FAILED or
   * CANCELLED.
   * </pre>
   *
   * <code>repeated .google.cloud.talent.v4.JobResult job_results = 3;</code>
   */
  com.google.cloud.talent.v4.JobResultOrBuilder getJobResultsOrBuilder(int index);
}
