// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

public interface DebugOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.DebugOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Specifies the level of debug output. The higher the number, the more
   * debug information is returned and printed in backend server logs.
   * Current levels are 1-4.
   * </pre>
   *
   * <code>int32 level = 1;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <pre>
   * Specifies which search backend to use. Current available options are:
   * st-bti, model-t, and st-muppet.
   * </pre>
   *
   * <code>string searcher = 2;</code>
   * @return The searcher.
   */
  java.lang.String getSearcher();
  /**
   * <pre>
   * Specifies which search backend to use. Current available options are:
   * st-bti, model-t, and st-muppet.
   * </pre>
   *
   * <code>string searcher = 2;</code>
   * @return The bytes for searcher.
   */
  com.google.protobuf.ByteString
      getSearcherBytes();

  /**
   * <pre>
   * Specifies the scoring parameters to override during search. This is
   * equivalent to the 'dsp' url parameter in the legacy system. For details,
   * consult go/gjobs-scoring-params.
   * </pre>
   *
   * <code>string scoring_parameter_override = 3;</code>
   * @return The scoringParameterOverride.
   */
  java.lang.String getScoringParameterOverride();
  /**
   * <pre>
   * Specifies the scoring parameters to override during search. This is
   * equivalent to the 'dsp' url parameter in the legacy system. For details,
   * consult go/gjobs-scoring-params.
   * </pre>
   *
   * <code>string scoring_parameter_override = 3;</code>
   * @return The bytes for scoringParameterOverride.
   */
  com.google.protobuf.ByteString
      getScoringParameterOverrideBytes();

  /**
   * <pre>
   * Overrides the ST sorting/scoring expression.
   * </pre>
   *
   * <code>string st_expression_override = 4;</code>
   * @return The stExpressionOverride.
   */
  java.lang.String getStExpressionOverride();
  /**
   * <pre>
   * Overrides the ST sorting/scoring expression.
   * </pre>
   *
   * <code>string st_expression_override = 4;</code>
   * @return The bytes for stExpressionOverride.
   */
  com.google.protobuf.ByteString
      getStExpressionOverrideBytes();

  /**
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   * @return Whether the searchAllTenant field is set.
   */
  boolean hasSearchAllTenant();
  /**
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   * @return The searchAllTenant.
   */
  com.google.protobuf.BoolValue getSearchAllTenant();
  /**
   * <pre>
   * Search documents of all tenants (only implemented for job search as of
   * 6/14/2019).
   * </pre>
   *
   * <code>.google.protobuf.BoolValue search_all_tenant = 5;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getSearchAllTenantOrBuilder();

  /**
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   * @return Whether the enableWildcardSearch field is set.
   */
  boolean hasEnableWildcardSearch();
  /**
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   * @return The enableWildcardSearch.
   */
  com.google.protobuf.BoolValue getEnableWildcardSearch();
  /**
   * <pre>
   * Temporarily added this flag for profile wildcard search
   * Flag to indicate whether wildcard search is enabled
   * </pre>
   *
   * <code>.google.protobuf.BoolValue enable_wildcard_search = 6;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getEnableWildcardSearchOrBuilder();
}
