// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

public interface DelegatedUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.DelegatedUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The GCP project number of the customer that the caller is acting on
   * behalf of.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>int64 project_number = 1;</code>
   * @return The projectNumber.
   */
  long getProjectNumber();

  /**
   * <pre>
   * The pretended distributor id.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>string distributor_id = 2;</code>
   * @return The distributorId.
   */
  java.lang.String getDistributorId();
  /**
   * <pre>
   * The pretended distributor id.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>string distributor_id = 2;</code>
   * @return The bytes for distributorId.
   */
  com.google.protobuf.ByteString
      getDistributorIdBytes();

  /**
   * <pre>
   * The pretended tenant id.
   * </pre>
   *
   * <code>string tenant_id = 3;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * The pretended tenant id.
   * </pre>
   *
   * <code>string tenant_id = 3;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();
}
