// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

/**
 * <pre>
 * Delegated partner information where for admin or debug purpose, our
 * internal source needs to act as a partner to do READ_ONLY operations (for
 * example, SearchJobs).
 * </pre>
 *
 * Protobuf type {@code google.cloud.talent.v4.DelegatedUserInfo}
 */
public final class DelegatedUserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.cloud.talent.v4.DelegatedUserInfo)
    DelegatedUserInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DelegatedUserInfo.newBuilder() to construct.
  private DelegatedUserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DelegatedUserInfo() {
    distributorId_ = "";
    tenantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DelegatedUserInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DelegatedUserInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            projectNumber_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            distributorId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.talent.v4.CommonProto.internal_static_google_cloud_talent_v4_DelegatedUserInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.talent.v4.CommonProto.internal_static_google_cloud_talent_v4_DelegatedUserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.talent.v4.DelegatedUserInfo.class, com.google.cloud.talent.v4.DelegatedUserInfo.Builder.class);
  }

  public static final int PROJECT_NUMBER_FIELD_NUMBER = 1;
  private long projectNumber_;
  /**
   * <pre>
   * The GCP project number of the customer that the caller is acting on
   * behalf of.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>int64 project_number = 1;</code>
   * @return The projectNumber.
   */
  @java.lang.Override
  public long getProjectNumber() {
    return projectNumber_;
  }

  public static final int DISTRIBUTOR_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object distributorId_;
  /**
   * <pre>
   * The pretended distributor id.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>string distributor_id = 2;</code>
   * @return The distributorId.
   */
  @java.lang.Override
  public java.lang.String getDistributorId() {
    java.lang.Object ref = distributorId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      distributorId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The pretended distributor id.
   * If both project number and distributor id are provided,
   * distributor id has the higher priority.
   * </pre>
   *
   * <code>string distributor_id = 2;</code>
   * @return The bytes for distributorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDistributorIdBytes() {
    java.lang.Object ref = distributorId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      distributorId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   * The pretended tenant id.
   * </pre>
   *
   * <code>string tenant_id = 3;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The pretended tenant id.
   * </pre>
   *
   * <code>string tenant_id = 3;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (projectNumber_ != 0L) {
      output.writeInt64(1, projectNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(distributorId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, distributorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tenantId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (projectNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, projectNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(distributorId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, distributorId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tenantId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.talent.v4.DelegatedUserInfo)) {
      return super.equals(obj);
    }
    com.google.cloud.talent.v4.DelegatedUserInfo other = (com.google.cloud.talent.v4.DelegatedUserInfo) obj;

    if (getProjectNumber()
        != other.getProjectNumber()) return false;
    if (!getDistributorId()
        .equals(other.getDistributorId())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROJECT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProjectNumber());
    hash = (37 * hash) + DISTRIBUTOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDistributorId().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.talent.v4.DelegatedUserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.talent.v4.DelegatedUserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Delegated partner information where for admin or debug purpose, our
   * internal source needs to act as a partner to do READ_ONLY operations (for
   * example, SearchJobs).
   * </pre>
   *
   * Protobuf type {@code google.cloud.talent.v4.DelegatedUserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.talent.v4.DelegatedUserInfo)
      com.google.cloud.talent.v4.DelegatedUserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.talent.v4.CommonProto.internal_static_google_cloud_talent_v4_DelegatedUserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.talent.v4.CommonProto.internal_static_google_cloud_talent_v4_DelegatedUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.talent.v4.DelegatedUserInfo.class, com.google.cloud.talent.v4.DelegatedUserInfo.Builder.class);
    }

    // Construct using com.google.cloud.talent.v4.DelegatedUserInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      projectNumber_ = 0L;

      distributorId_ = "";

      tenantId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.talent.v4.CommonProto.internal_static_google_cloud_talent_v4_DelegatedUserInfo_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DelegatedUserInfo getDefaultInstanceForType() {
      return com.google.cloud.talent.v4.DelegatedUserInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DelegatedUserInfo build() {
      com.google.cloud.talent.v4.DelegatedUserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.talent.v4.DelegatedUserInfo buildPartial() {
      com.google.cloud.talent.v4.DelegatedUserInfo result = new com.google.cloud.talent.v4.DelegatedUserInfo(this);
      result.projectNumber_ = projectNumber_;
      result.distributorId_ = distributorId_;
      result.tenantId_ = tenantId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.talent.v4.DelegatedUserInfo) {
        return mergeFrom((com.google.cloud.talent.v4.DelegatedUserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.talent.v4.DelegatedUserInfo other) {
      if (other == com.google.cloud.talent.v4.DelegatedUserInfo.getDefaultInstance()) return this;
      if (other.getProjectNumber() != 0L) {
        setProjectNumber(other.getProjectNumber());
      }
      if (!other.getDistributorId().isEmpty()) {
        distributorId_ = other.distributorId_;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.talent.v4.DelegatedUserInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.talent.v4.DelegatedUserInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long projectNumber_ ;
    /**
     * <pre>
     * The GCP project number of the customer that the caller is acting on
     * behalf of.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>int64 project_number = 1;</code>
     * @return The projectNumber.
     */
    @java.lang.Override
    public long getProjectNumber() {
      return projectNumber_;
    }
    /**
     * <pre>
     * The GCP project number of the customer that the caller is acting on
     * behalf of.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>int64 project_number = 1;</code>
     * @param value The projectNumber to set.
     * @return This builder for chaining.
     */
    public Builder setProjectNumber(long value) {
      
      projectNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The GCP project number of the customer that the caller is acting on
     * behalf of.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>int64 project_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectNumber() {
      
      projectNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object distributorId_ = "";
    /**
     * <pre>
     * The pretended distributor id.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>string distributor_id = 2;</code>
     * @return The distributorId.
     */
    public java.lang.String getDistributorId() {
      java.lang.Object ref = distributorId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        distributorId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The pretended distributor id.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>string distributor_id = 2;</code>
     * @return The bytes for distributorId.
     */
    public com.google.protobuf.ByteString
        getDistributorIdBytes() {
      java.lang.Object ref = distributorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        distributorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The pretended distributor id.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>string distributor_id = 2;</code>
     * @param value The distributorId to set.
     * @return This builder for chaining.
     */
    public Builder setDistributorId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      distributorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The pretended distributor id.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>string distributor_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistributorId() {
      
      distributorId_ = getDefaultInstance().getDistributorId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The pretended distributor id.
     * If both project number and distributor id are provided,
     * distributor id has the higher priority.
     * </pre>
     *
     * <code>string distributor_id = 2;</code>
     * @param value The bytes for distributorId to set.
     * @return This builder for chaining.
     */
    public Builder setDistributorIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      distributorId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * The pretended tenant id.
     * </pre>
     *
     * <code>string tenant_id = 3;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The pretended tenant id.
     * </pre>
     *
     * <code>string tenant_id = 3;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The pretended tenant id.
     * </pre>
     *
     * <code>string tenant_id = 3;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The pretended tenant id.
     * </pre>
     *
     * <code>string tenant_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The pretended tenant id.
     * </pre>
     *
     * <code>string tenant_id = 3;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.cloud.talent.v4.DelegatedUserInfo)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.talent.v4.DelegatedUserInfo)
  private static final com.google.cloud.talent.v4.DelegatedUserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.talent.v4.DelegatedUserInfo();
  }

  public static com.google.cloud.talent.v4.DelegatedUserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DelegatedUserInfo>
      PARSER = new com.google.protobuf.AbstractParser<DelegatedUserInfo>() {
    @java.lang.Override
    public DelegatedUserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DelegatedUserInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DelegatedUserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DelegatedUserInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.talent.v4.DelegatedUserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

