// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/job_service.proto

package com.google.cloud.talent.v4;

public interface PurgeJobsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.PurgeJobsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The resource name of the project under which the jobs should be deleted.
   * The format is "projects/{project_id}". For example, "projects/foo".
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The resource name of the project under which the jobs should be deleted.
   * The format is "projects/{project_id}". For example, "projects/foo".
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Required. A filter matching the jobs to be purged.
   * The filter can be one of the following three parent resources.
   * 1. Company. Resource name of the company under which all the jobs should be
   * deleted. The format is
   * "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}". For
   * example, "projects/foo/tenants/bar/companies/baz"
   * 2. Tenant. Resource name of the tenant under which all the jobs should be
   * deleted. The format is "projects/{project_id}/tenants/{tenant_id}". For
   * example, "projects/foo/tenants/bar".
   * 3. Project. Resource name of the project under which all the jobs should be
   * deleted. The format is "projects/{project_id}". For example,
   * "projects/foo/".
   * </pre>
   *
   * <code>string filter = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The filter.
   */
  java.lang.String getFilter();
  /**
   * <pre>
   * Required. A filter matching the jobs to be purged.
   * The filter can be one of the following three parent resources.
   * 1. Company. Resource name of the company under which all the jobs should be
   * deleted. The format is
   * "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}". For
   * example, "projects/foo/tenants/bar/companies/baz"
   * 2. Tenant. Resource name of the tenant under which all the jobs should be
   * deleted. The format is "projects/{project_id}/tenants/{tenant_id}". For
   * example, "projects/foo/tenants/bar".
   * 3. Project. Resource name of the project under which all the jobs should be
   * deleted. The format is "projects/{project_id}". For example,
   * "projects/foo/".
   * </pre>
   *
   * <code>string filter = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for filter.
   */
  com.google.protobuf.ByteString
      getFilterBytes();

  /**
   * <pre>
   * Actually perform the purge.
   * If `force` is set to false, the method will return a sample of
   * resource names that will be deleted.
   * </pre>
   *
   * <code>bool force = 3;</code>
   * @return The force.
   */
  boolean getForce();
}
