// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/talent/v4/common.proto

package com.google.cloud.talent.v4;

public interface ResponseMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.talent.v4.ResponseMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A unique id associated with this call.
   * This id is logged for tracking purposes.
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   * A unique id associated with this call.
   * This id is logged for tracking purposes.
   * </pre>
   *
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>.google.cloud.talent.v4.DebugInfo debug_info = 2;</code>
   * @return Whether the debugInfo field is set.
   */
  boolean hasDebugInfo();
  /**
   * <code>.google.cloud.talent.v4.DebugInfo debug_info = 2;</code>
   * @return The debugInfo.
   */
  com.google.cloud.talent.v4.DebugInfo getDebugInfo();
  /**
   * <code>.google.cloud.talent.v4.DebugInfo debug_info = 2;</code>
   */
  com.google.cloud.talent.v4.DebugInfoOrBuilder getDebugInfoOrBuilder();
}
